dist: xenial
language: python
jobs:
    include:
        - name: "PyBML test on Xenial Linux with Python 3.7"
          python: 3.7
install: 
    #- pip3 install -r requirements.txt
    - python setup.py install
    - pip install coverage
script: 
    - cd test_script
    # - python3 test_meta_init.py
    - coverage run -p test_model.py
    - coverage run -p test_optmizer.py
    - coverage run  -p test_system_init.py
    - coverage run  -p test_sistem_feature.py
    - coverage combine

after_success:
  - bash <(curl -s https://codecov.io/bash)
